version: '3'
services:

  spring-boot:
    image: salsabil1/springprojet
    container_name: spring
    ports:
      - 8082:8082
    depends_on:
      - database
    networks:
      - AppNet 
    restart: on-failure     

networks:
  AppNet:
